### PR TITLE
[ARRCONN-227] Port to use the new findByID interface

### PR DESCRIPTION
**Pull request by vladimir-trifonov**
https://jira.appcelerator.org/browse/ARRCONN-227

### CODE REVIEW

**Review by janvennemann — CHANGES_REQUESTED** [review]
The fallback delegating findOne to findById is missing here, please add. The rest looks good!

**Review by janvennemann — APPROVED** [review]

**Comment by alasdairhurst** [comment]
@janvennemann Is this ok to be merged? Just wondering if there was a reason for holding off the merge of this one and not the rest of the findByID changes

**Comment by janvennemann** [comment]
@alasdairhurst, the reason we were holding this of is because of all the broken connector tests which resulted in them not getting published. Without the changes being available to the other connectors we waited with the merge to the composite connector. 
I think @vladimir-trifonov recently changed to connector builds to skip tests so most of the changes should finally be available and we can continue with this. I'm not working on connectors anymore so Vladimir should have a better insight. From a pure code point of view this is ready to be merged.

**Comment by alasdairhurst** [comment]
@janvennemann if it's good from a code perspective then it should be able to be merged!

**Pull request merged**
