### PR TITLE
[API-1295] model.findall does not show all

### PR DESCRIPTION
**Pull request by pltod2**
Problem: When having join models with child relationship of type Array we are not able to take more than default number of 10 children.

Solution: Now we support specifying the limit property for the number of children fetched as defined in the model bellow. The valid limit specified is between 1 and 1000 otherwise the application will work with default number of 10 children fetched.

``` javascript
var Arrow = require('arrow');

var Model = Arrow.createModel('QWP', {
    fields: {
        Question: {
            model: 'Question',
            type: Object
        },
        Responses: {
            model: 'Response',
            type: Array,
            limit: 500
        }
    },
    connector: 'appc.composite',
    actions: [
        'read'
    ],
    metadata: {
        left_join: [
            {
                model: 'Response',
                multiple: true,
                join_properties: {
                    QuestionID: 'QuestionID'
                }
            }
        ]
    }
});

module.exports = Model;
```

### CODE REVIEW

**Comment by pltod2** [comment]
JIRA: https://jira.appcelerator.org/browse/API-1295

**Comment by janvennemann** [comment]
Functionality tested locally, the limit parameter works as expected. Could you also edit the [Joining with Multiple Children](https://github.com/appcelerator/appc.composite#joining-with-multiple-children) chapter of the Readme and mention the limit parameter and it's default value? Apart from that, looks good to me!

**Comment by pltod2** [comment]
Documentation updated!

**Comment by janvennemann** [comment]
Perfect! CR and FT passed and hereby approved!

**Pull request merged**
